"""Build a dependency-free personal site. Run: python scripts/build.py."""
from pathlib import Path
import json, html, re
ROOT = Path(__file__).resolve().parents[1]
BASE = 'https://mehmetakifaksoy.github.io'
def save(path, text):
    target = ROOT / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding='utf-8')
def page(title, description, path, body):
    e = html.escape
    return f'''<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)} | Mehmet Akif Aksoy</title><meta name="description" content="{e(description)}"><link rel="canonical" href="{BASE}{path}"><meta property="og:type" content="website"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(description)}"><meta property="og:url" content="{BASE}{path}"><meta property="og:image" content="{BASE}/assets/prompt-injection.jpg"><meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#f5f3ed"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/site.css"></head><body><a class="skip" href="#main">İçeriğe geç</a>{nav()}<main id="main" class="wrap">{body}</main><footer><span>© 2026 Mehmet Akif Aksoy · Uygulamalı öğrenme notları</span><a href="https://github.com/mehmetakifaksoy">GitHub ↗</a></footer></body></html>'''
def nav():
    return '<nav aria-label="Ana menü"><a class="brand" href="/">Mehmet Akif Aksoy<span>AI SECURITY / PERSONAL NOTES</span></a><div class="links"><a href="/yazilar/">Yazılar</a><a href="/projeler/">Projeler</a><a href="/hakkimda/">Hakkımda</a><a href="https://github.com/mehmetakifaksoy">GitHub ↗</a></div></nav>'
posts=json.loads((ROOT/'content/articles.json').read_text(encoding='utf-8'))
def card(p):
    return f'<article class="card"><span class="tag">{p["category"]}</span><h3><a href="/yazilar/{p["slug"]}/">{p["title"]} ↗</a></h3><p>{p["summary"]}</p><div class="meta">İlk yayın: {p.get("published", "2021")} · Güncelleme: {p.get("updated", "5 Ekim 2026")}</div></article>'
feature='''<section class="feature"><div><div class="eyebrow">Öne çıkan çalışma · Etkileşimli deney</div><h2>Bir belge, asistanınıza talimat verirse?</h2><p>Yerel RAG laboratuvarından bir prompt injection deneyi. Benzerlik eşiğini değiştirin; hangi belgenin bağlama girdiğini ve kaynak kontrolünün neyi yakaladığını görün.</p><p class="meta">Python · Ollama · Semantic search · Prompt injection</p><a class="button" href="/prompt-injection/">Simülasyonu aç →</a></div><a href="/prompt-injection/" aria-label="Prompt injection simülasyonunu aç"><img src="/assets/prompt-injection.jpg" alt="Asistanınız belgeyi okuyor. Peki ya belge talimat veriyorsa? Başlıklı prompt injection görseli" width="900" height="1125"></a></section>'''
project='''<section class="project"><div><div class="eyebrow">Açık kaynak laboratuvar</div><h2>AI Security Fundamentals Lab</h2><p>Metinden embedding'e, semantic search'ten yerel RAG'e uzanan küçük bir Python projesi. Güven sınırlarını gözlemlenebilir deneylerle inceliyorum.</p><a class="button" href="https://github.com/mehmetakifaksoy/ai-security-fundamentals-lab">Kodu ve kurulumu incele ↗</a></div><div><h3>Laboratuvarda neler var?</h3><ul><li>Embedding benzerliği ve kaynak getirme</li><li>Ollama üzerinden yerel model ile cevap üretimi</li><li>Sentetik prompt injection test verisi</li><li>Kaynak etiketi kontrolü ve benzerlik filtresi</li></ul><a href="https://github.com/mehmetakifaksoy/ai-security-fundamentals-lab/blob/main/evaluation.md">Deney kayıtları ve sınırlamalar ↗</a></div></section>'''
home='''<header class="hero"><div class="eyebrow">Mehmet Akif Aksoy / Kişisel çalışma alanı</div><h1>AI Security.<br>Okuyarak, kurarak,<br>deneyerek.</h1><p class="lead">Yapay zekâ uygulamalarında verinin, talimatın ve yetkinin nerede ayrıldığını öğreniyorum. Burada kurduğum laboratuvarları, gözlemlediğim sonuçları ve teknik notlarımı paylaşıyorum.</p><div class="actions"><a class="button" href="/prompt-injection/">Son deneyi incele →</a><a class="button secondary" href="/hakkimda/">Beni tanıyın</a></div></header>'''+feature+'<section class="section">'+project+'</section><section class="section"><div class="section-head"><h2>Temeller hâlâ önemli.</h2><a href="/yazilar/">Tüm yazılar →</a></div><p>Ağ ve sistem güvenliği notlarımın güncellenmiş sürümleri. Eski içerikleri daha açık, daha doğru bir başlangıç noktası hâline getirdim.</p><div class="cards">'+''.join(card(p) for p in posts)+'</div></section>'
save('index.html',page('AI Security, uygulamalı','Mehmet Akif Aksoy: AI Security laboratuvarları, etkileşimli prompt injection deneyi ve Türkçe teknik notlar.','/',home))
save('yazilar/index.html',page('Yazılar','AI Security deneyleri ve güncellenmiş ağ güvenliği temelleri.','/yazilar/','<header class="hero"><div class="eyebrow">Çalışma günlüğü</div><h1>Deneyler ve teknik notlar.</h1><p class="lead">Sonuçları, sınırlamaları ve kaynakları birlikte paylaşmak için.</p></header>'+feature+'<section class="section"><h2>Arşivden: güncellenmiş temeller</h2><div class="cards">'+''.join(card(p) for p in posts)+'</div></section>'))
save('projeler/index.html',page('Projeler','Python, yerel RAG ve AI Security üzerine uygulamalı çalışmalar.','/projeler/','<header class="hero"><div class="eyebrow">Kod / Deney / Gözlem</div><h1>Çalışan örnekler.<br>Açık sonuçlar.</h1><p class="lead">Küçük, anlaşılır laboratuvarlarla başlayıp güvenlik davranışlarını adım adım inceliyorum.</p></header>'+project+'<section class="section">'+feature+'</section>'))
save('hakkimda/index.html',page('Hakkımda','Mehmet Akif Aksoy ve uygulamalı AI Security öğrenme çalışmaları.','/hakkimda/','''<article class="article"><div class="eyebrow">Merhaba, ben Mehmet Akif.</div><h1>Merakımı çalışan<br>projelere dönüştürüyorum.</h1><p class="lead">Linux, Python ve güvenlik ilgimi bugün yapay zekâ uygulamalarının güven sınırlarını anlamaya taşıyorum.</p><p>Bu site, öğrenirken tuttuğum notların ve geliştirdiğim küçük projelerin kişisel arşivi. Özellikle RAG sistemleri, prompt injection, kaynak güvenilirliği ve araç yetkileri üzerine çalışıyorum.</p><h2>Nasıl çalışıyorum?</h2><p>Önce basit bir örnek kuruyor, ardından farklı sorular ve test verileriyle davranışını inceliyorum. Bir deney başarılı olduğunda da neyi göstermediğini yazıyorum. Kaynak etiketi doğrulamasının doğruluk kontrolü olmadığını, benzerliğin güven anlamına gelmediğini bu yaklaşım sayesinde daha somut görebiliyorum.</p><h2>Bu sitede ne bulacaksınız?</h2><p>Yerel modellerle yaptığım uygulamalar, yeniden düzenlediğim ağ temelleri ve tarayıcıda deneyebileceğiniz bir prompt injection simülasyonu. Yazılar eğitim ve deney notlarıdır; kapsamlarını ve sınırlamalarını ilgili sayfalarda belirtiyorum.</p><h2>İletişim ve çalışmalar</h2><p>Projelerimi GitHub üzerinden takip edebilir, ilgili depoda bir issue açarak soru veya düzeltme paylaşabilirsiniz.</p><a class="button" href="https://github.com/mehmetakifaksoy">GitHub profilim ↗</a></article>'''))
for p in posts:
    path=f'/yazilar/{p["slug"]}/'
    body=f'<article class="article"><a href="/yazilar/">← Yazılar</a><p class="eyebrow">{p["category"]}</p><h1>{p["title"]}</h1><p class="lead">{p["summary"]}</p><p class="meta">Mehmet Akif Aksoy · İlk yayın: {p.get("published", "2021")} · Güncelleme: {p.get("updated", "5 Ekim 2026")}</p><div class="notice">{p.get("note", "2021 tarihli kişisel notun yeniden düzenlenmiş sürümü. Eski anlatımdaki teknik hatalar düzeltildi; güncel sürüm bu sayfada tutuluyor.")}</div>{p["body"]}<h2>Kaynaklar ve devamı</h2><ul>'+''.join(f'<li><a href="{u}">{t} ↗</a></li>' for t,u in p['sources'])+'</ul><p><a href="/prompt-injection/">Bu temelleri AI Security deneyine bağlayın →</a></p></article>'
    save(path.strip('/')+'/index.html',page(p['title'],p['summary'],path,body))
    if p.get('legacy'): save(p['legacy'],f'<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{p["title"]}</title><link rel="canonical" href="{BASE}{path}"><meta http-equiv="refresh" content="0;url={path}"></head><body><p>Bu yazı güncellendi. <a href="{path}">{p["title"]}</a></p></body></html>')
save('archive.html','<!doctype html><html lang="tr"><head><meta charset="utf-8"><title>Yazı arşivi</title><meta http-equiv="refresh" content="0;url=/yazilar/"></head><body><a href="/yazilar/">Yazı arşivi</a></body></html>')
sim=(ROOT/'content/simulation.html').read_text(encoding='utf-8-sig')
sim=re.sub(r'<nav>.*?</nav>',nav(),sim,flags=re.S)
sim=sim.replace('</head>','<link rel="canonical" href="'+BASE+'/prompt-injection/"><meta property="og:title" content="Bir belge talimat vermeye başlarsa"><meta property="og:image" content="'+BASE+'/assets/prompt-injection.jpg"><link rel="icon" href="/assets/favicon.svg"><style>.brand{text-decoration:none;font-weight:700}.brand span{display:block;font-size:11px;color:var(--muted)}.links{display:flex;gap:18px;flex-wrap:wrap}@media(max-width:600px){nav{flex-direction:column}.links{gap:12px}}</style></head>')
save('prompt-injection/index.html',sim)
paths=['/','/yazilar/','/projeler/','/hakkimda/','/prompt-injection/']+[f'/yazilar/{p["slug"]}/' for p in posts]
save('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{BASE}{p}</loc><lastmod>2026-10-05</lastmod></url>' for p in paths)+'</urlset>')
save('robots.txt',f'User-agent: *\nAllow: /\nSitemap: {BASE}/sitemap.xml\n')
save('.nojekyll','')
save('assets/favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#202421"/><text x="32" y="43" fill="#d5ec99" font-family="sans-serif" font-size="33" font-weight="700" text-anchor="middle">M</text></svg>')
print(f'Built {len(paths)} pages; preserved {len(posts)} legacy article URLs.')
